// Renders the app icon set and store graphics from SVG with a headless Chromium.
//   node scripts/make-assets.mjs
// Needs Playwright with Chromium (PLAYWRIGHT_BROWSERS_PATH). No network access.
import { createRequire } from 'node:module';
import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE ?? '/opt/node-tools/node_modules/playwright');
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const VIOLET_TOP = '#8B73FF';
const VIOLET_BOTTOM = '#4B2BD0';

// A flame with a check mark cut into it. Designed on a 1024 canvas, centred.
const flame = (id, { fill, check }) => `
  <defs>
    <linearGradient id="${id}-f" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#FFC15A"/><stop offset="1" stop-color="#FF6A00"/>
    </linearGradient>
  </defs>
  <path d="M512 130 C 548 250 700 322 700 530 C 700 700 612 800 512 800 C 412 800 324 700 324 530
           C 324 438 366 382 412 330 C 418 396 446 432 484 436 C 466 330 470 226 512 130 Z"
        fill="${fill ?? `url(#${id}-f)`}"/>
  <path d="M424 580 L494 650 L606 508" fill="none" stroke="${check}" stroke-width="52"
        stroke-linecap="round" stroke-linejoin="round"/>`;

const svg = (w, h, body) => `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">${body}</svg>`;
const bg = (w, h) => `
  <defs><linearGradient id="bg" x1="0" y1="0" x2="0.4" y2="1">
    <stop offset="0" stop-color="${VIOLET_TOP}"/><stop offset="1" stop-color="${VIOLET_BOTTOM}"/>
  </linearGradient></defs>
  <rect width="${w}" height="${h}" fill="url(#bg)"/>`;
const scaled = (s, inner) => `<g transform="translate(${512 - 512 * s} ${512 - 512 * s}) scale(${s})">${inner}</g>`;

const icon = svg(1024, 1024, bg(1024, 1024) + scaled(1.05, flame('a', { check: '#FFFFFF' })));
// Adaptive icons keep important art inside the central 66%.
const adaptiveFg = svg(1024, 1024, scaled(0.72, flame('b', { check: '#FFFFFF' })));
const monochrome = svg(1024, 1024, scaled(0.72, flame('c', { fill: '#000000', check: '#FFFFFF' }).replace('stroke="#FFFFFF"', 'stroke="#FFFFFF"')));
const splash = svg(1024, 1024, scaled(0.8, flame('d', { check: '#FFFFFF' })));

// Feature graphic: title and tagline on the left, a faint heatmap and the flame on the right.
const cells = [];
for (let c = 0; c < 13; c++) {
  for (let r = 0; r < 7; r++) {
    const v = (c * 7 + r * 13 + (c % 3) * 5) % 10;
    const o = v < 3 ? 0.06 : v < 5 ? 0.14 : v < 7 ? 0.24 : v < 9 ? 0.38 : 0.55;
    cells.push(`<rect x="${664 + c * 26}" y="${58 + r * 26 + (c % 2) * 3}" width="20" height="20" rx="5" fill="#fff" fill-opacity="${o}"/>`);
  }
}
const feature = `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="500" viewBox="0 0 1024 500">
  ${bg(1024, 500)}
  ${cells.join('')}
  <g transform="translate(690 175) scale(0.36)">${flame('e', { check: '#FFFFFF' })}</g>
  <text x="64" y="215" font-family="Inter, Helvetica, Arial, sans-serif" font-weight="800" font-size="84" fill="#fff">Habit Tracker</text>
  <text x="66" y="290" font-family="Inter, Helvetica, Arial, sans-serif" font-weight="600" font-size="40" fill="#fff" fill-opacity="0.92">Streaks &amp; widget, no paywall</text>
</svg>`;

const jobs = [
  ['assets/icon.png', icon, 1024, 1024, false],
  ['assets/adaptive-icon-foreground.png', adaptiveFg, 1024, 1024, true],
  ['assets/adaptive-icon-monochrome.png', monochrome, 1024, 1024, true],
  ['assets/splash-icon.png', splash, 1024, 1024, true],
  ['store/icon-512.png', icon, 512, 512, false],
  ['store/feature-graphic-1024x500.png', feature, 1024, 500, false],
];

mkdirSync(resolve(root, 'assets'), { recursive: true });
mkdirSync(resolve(root, 'store'), { recursive: true });
const browser = await chromium.launch();
for (const [file, markup, w, h, transparent] of jobs) {
  const page = await browser.newPage({ viewport: { width: w, height: h }, deviceScaleFactor: 1 });
  await page.setContent(`<html><body style="margin:0;background:transparent">${markup.replace(/width="\d+" height="\d+"/, `width="${w}" height="${h}"`)}</body></html>`);
  await page.screenshot({ path: resolve(root, file), omitBackground: transparent, clip: { x: 0, y: 0, width: w, height: h } });
  await page.close();
  console.log('wrote', file);
}
await browser.close();
writeFileSync(resolve(root, 'assets/.generated'), 'Generated by scripts/make-assets.mjs\n');
