// Renders the app icon set and store graphics.
//   node scripts/make-assets.mjs
// Needs Playwright with Chromium (PLAYWRIGHT_BROWSERS_PATH). No network access.
import { createRequire } from 'node:module';
import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE ?? '/opt/node-tools/node_modules/playwright');
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const INDIGO = '#4F46E5';
const GOLD = '#F59E0B';
const FONT = 'Inter, Verdana, Arial, sans-serif';

// ASO.md §5: a white speech bubble with a bold "?" whose dot is a gold bulb, on indigo.
const art = ({ bubble, ink, dot }) =>
  `<path d="M232 250 Q232 150 332 150 H692 Q792 150 792 250 V560 Q792 660 692 660 H470 L330 800 V660 H332 Q232 660 232 560 Z" fill="${bubble}"/>` +
  `<path d="M420 330 Q420 250 512 250 Q604 250 604 330 Q604 390 548 430 Q512 456 512 500" fill="none" stroke="${ink}" stroke-width="64" stroke-linecap="round"/>` +
  `<circle cx="512" cy="590" r="44" fill="${dot}"/>` +
  `<rect x="494" y="626" width="36" height="18" rx="6" fill="${dot}"/>`;

const svg = (w, h, body) => `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">${body}</svg>`;
const scaled = (s, inner) => `<g transform="translate(${512 - 512 * s} ${512 - 512 * s}) scale(${s})">${inner}</g>`;
const full = art({ bubble: '#FFFFFF', ink: INDIGO, dot: GOLD });

const icon = svg(1024, 1024, `<defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${INDIGO}"/><stop offset="1" stop-color="#6366F1"/></linearGradient></defs><rect width="1024" height="1024" fill="url(#g)"/>${scaled(0.96, full)}`);
const adaptiveFg = svg(1024, 1024, scaled(0.66, full));
const mono = svg(1024, 1024, scaled(0.66, art({ bubble: '#000', ink: '#fff', dot: '#fff' })));
const splash = svg(1024, 1024, scaled(0.8, art({ bubble: INDIGO, ink: '#FFFFFF', dot: GOLD })));
const feature = `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="500" viewBox="0 0 1024 500">
  <defs><linearGradient id="f" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${INDIGO}"/><stop offset="1" stop-color="#312E81"/></linearGradient></defs>
  <rect width="1024" height="500" fill="url(#f)"/>
  <g transform="translate(600 40) scale(0.42)">${full}</g>
  <text x="56" y="215" font-family="${FONT}" font-weight="800" font-size="104" fill="#fff">Quizora</text>
  <text x="60" y="290" font-family="${FONT}" font-weight="700" font-size="44" fill="${GOLD}">Trivia that works offline.</text>
  <text x="60" y="350" font-family="${FONT}" font-size="30" fill="#fff" fill-opacity="0.95">Daily challenge. A fun fact with every answer.</text>
</svg>`;

const jobs = [
  ['assets/icon.png', icon, 1024, 1024, false],
  ['assets/adaptive-icon-foreground.png', adaptiveFg, 1024, 1024, true],
  ['assets/adaptive-icon-monochrome.png', mono, 1024, 1024, true],
  ['assets/splash-icon.png', splash, 1024, 1024, true],
  ['store/icon-512.png', icon, 512, 512, false],
  ['store/feature-graphic-1024x500.png', feature, 1024, 500, false],
];

mkdirSync(resolve(root, 'assets'), { recursive: true });
mkdirSync(resolve(root, 'store'), { recursive: true });
const browser = await chromium.launch();
for (const [file, markup, w, h, transparent] of jobs) {
  const page = await browser.newPage({ viewport: { width: w, height: h }, deviceScaleFactor: 1 });
  await page.setContent(`<html><body style="margin:0;background:transparent">${markup.replace(/width="\d+" height="\d+"/, `width="${w}" height="${h}"`)}</body></html>`);
  await page.screenshot({ path: resolve(root, file), omitBackground: transparent, clip: { x: 0, y: 0, width: w, height: h } });
  await page.close();
  console.log('wrote', file);
}
await browser.close();
writeFileSync(resolve(root, 'assets/.generated'), 'Generated by scripts/make-assets.mjs\n');
