// Renders the app icon set and store graphics.
//   node scripts/make-assets.mjs
// Needs Playwright with Chromium (PLAYWRIGHT_BROWSERS_PATH). No network access.
import { createRequire } from 'node:module';
import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE ?? '/opt/node-tools/node_modules/playwright');
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const BLUE = '#1F5FAF';
const CREAM = '#FBF7EF';

// A 3x3 block of big letters with the word "WORD" style highlight and a magnifier, on a 1024 canvas.
const letters = [
  ['W', 'O', 'R'],
  ['D', 'S', 'E'],
  ['A', 'R', 'C'],
];
const art = ({ card, ink, hi, ring }) => {
  const cell = 200;
  const x0 = 512 - 1.5 * cell;
  const y0 = 470 - 1.5 * cell;
  let out = `<rect x="${x0 - 30}" y="${y0 - 30}" width="${cell * 3 + 60}" height="${cell * 3 + 60}" rx="56" fill="${card}"/>`;
  // highlighted word across the top row
  out += `<rect x="${x0 + 8}" y="${y0 + 22}" width="${cell * 3 - 16}" height="${cell - 44}" rx="${(cell - 44) / 2}" fill="${hi}"/>`;
  letters.forEach((row, r) =>
    row.forEach((ch, c) => {
      out += `<text x="${x0 + c * cell + cell / 2}" y="${y0 + r * cell + cell / 2 + 36}" text-anchor="middle" font-family="Atkinson Hyperlegible, Verdana, Arial, sans-serif" font-weight="700" font-size="112" fill="${ink}">${ch}</text>`;
    }),
  );
  // magnifier
  out += `<circle cx="690" cy="690" r="120" fill="none" stroke="${ring}" stroke-width="34"/>`;
  out += `<path d="M778 778 L890 890" stroke="${ring}" stroke-width="46" stroke-linecap="round"/>`;
  return out;
};

const svg = (w, h, body) => `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">${body}</svg>`;
const scaled = (s, inner) => `<g transform="translate(${512 - 512 * s} ${512 - 512 * s}) scale(${s})">${inner}</g>`;
const full = art({ card: CREAM, ink: '#1B1B1F', hi: '#F4A261', ring: '#FFD166' });

const icon = svg(1024, 1024, `<rect width="1024" height="1024" fill="${BLUE}"/>${scaled(0.96, full)}`);
const adaptiveFg = svg(1024, 1024, scaled(0.66, full));
const mono = svg(1024, 1024, scaled(0.66, art({ card: '#000', ink: '#fff', hi: '#fff', ring: '#000' }).replace(/fill="#fff"\/>/g, 'fill="#fff" fill-opacity="0.0"/>')));
const splash = svg(1024, 1024, scaled(0.8, full));
const feature = `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="500" viewBox="0 0 1024 500">
  <rect width="1024" height="500" fill="${BLUE}"/>
  <g transform="translate(560 20) scale(0.46)">${full}</g>
  <text x="56" y="205" font-family="Atkinson Hyperlegible, Verdana, Arial, sans-serif" font-weight="700" font-size="84" fill="#fff">Word Search</text>
  <text x="58" y="285" font-family="Atkinson Hyperlegible, Verdana, Arial, sans-serif" font-weight="700" font-size="44" fill="#fff">Large Print Easy</text>
  <text x="58" y="350" font-family="Atkinson Hyperlegible, Verdana, Arial, sans-serif" font-size="30" fill="#fff" fill-opacity="0.95">Big letters. No timers. Offline.</text>
</svg>`;

const jobs = [
  ['assets/icon.png', icon, 1024, 1024, false],
  ['assets/adaptive-icon-foreground.png', adaptiveFg, 1024, 1024, true],
  ['assets/adaptive-icon-monochrome.png', mono, 1024, 1024, true],
  ['assets/splash-icon.png', splash, 1024, 1024, true],
  ['store/icon-512.png', icon, 512, 512, false],
  ['store/feature-graphic-1024x500.png', feature, 1024, 500, false],
];

mkdirSync(resolve(root, 'assets'), { recursive: true });
mkdirSync(resolve(root, 'store'), { recursive: true });
const browser = await chromium.launch();
for (const [file, markup, w, h, transparent] of jobs) {
  const page = await browser.newPage({ viewport: { width: w, height: h }, deviceScaleFactor: 1 });
  await page.setContent(`<html><body style="margin:0;background:transparent">${markup.replace(/width="\d+" height="\d+"/, `width="${w}" height="${h}"`)}</body></html>`);
  await page.screenshot({ path: resolve(root, file), omitBackground: transparent, clip: { x: 0, y: 0, width: w, height: h } });
  await page.close();
  console.log('wrote', file);
}
await browser.close();
writeFileSync(resolve(root, 'assets/.generated'), 'Generated by scripts/make-assets.mjs\n');
