// Renders the app icon set and store graphics (ASO.md §5: a teal "giant button" circle with a coral ring and a crescent).
//   node scripts/make-assets.mjs
// Needs Playwright with Chromium (PLAYWRIGHT_BROWSERS_PATH). No network access.
import { createRequire } from 'node:module';
import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE ?? '/opt/node-tools/node_modules/playwright');
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const CREAM = '#FBF7F4';
const TEAL = '#3E9C95';
const CORAL = '#E07A5F';
const INK = '#2B2D42';

// The button (a teal disc), the thin coral stopwatch ring around it, and a white crescent inside.
const art = ({ disc, ring, moon, id = 'm' }) => `
  <circle cx="512" cy="512" r="300" fill="${disc}"/>
  <path d="M512 112 A400 400 0 1 1 232 230" fill="none" stroke="${ring}" stroke-width="40" stroke-linecap="round"/>
  <mask id="${id}"><rect width="1024" height="1024" fill="#fff"/><circle cx="560" cy="470" r="120" fill="#000"/></mask>
  <circle cx="512" cy="512" r="150" fill="${moon}" mask="url(#${id})"/>`;

const svg = (w, h, body) => `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">${body}</svg>`;
const scaled = (s, inner) => `<g transform="translate(${512 - 512 * s} ${512 - 512 * s}) scale(${s})">${inner}</g>`;
const full = art({ disc: TEAL, ring: CORAL, moon: '#FFFFFF' });

const icon = svg(1024, 1024, `<rect width="1024" height="1024" fill="${CREAM}"/>${scaled(0.92, full)}`);
const adaptiveFg = svg(1024, 1024, scaled(0.62, full));
const mono = svg(1024, 1024, scaled(0.62, art({ disc: '#000', ring: '#000', moon: '#fff', id: 'mm' })));
const splash = svg(1024, 1024, scaled(0.8, full));
const feature = `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="500" viewBox="0 0 1024 500">
  <rect width="1024" height="500" fill="${CREAM}"/>
  <rect x="70" y="40" width="250" height="440" rx="36" fill="#000"/>
  <circle cx="195" cy="290" r="82" fill="#8C1E14" stroke="#FF6B5A" stroke-width="5"/>
  <text x="195" y="300" text-anchor="middle" font-family="Verdana, Arial, sans-serif" font-weight="700" font-size="32" fill="#FF8272">Stop</text>
  <text x="195" y="175" text-anchor="middle" font-family="Verdana, Arial, sans-serif" font-weight="700" font-size="58" fill="#FF6B5A">0:47</text>
  <text x="195" y="450" text-anchor="middle" font-family="Verdana, Arial, sans-serif" font-size="18" fill="#D65A4B">Night mode</text>
  <text x="380" y="190" font-family="Verdana, Arial, sans-serif" font-weight="700" font-size="60" fill="${INK}">One tap.</text>
  <text x="380" y="262" font-family="Verdana, Arial, sans-serif" font-weight="700" font-size="60" fill="${INK}">Calm numbers.</text>
  <text x="380" y="334" font-family="Verdana, Arial, sans-serif" font-weight="700" font-size="60" fill="${INK}">Ready for your</text>
  <text x="380" y="406" font-family="Verdana, Arial, sans-serif" font-weight="700" font-size="60" fill="${INK}">midwife.</text>
  <text x="382" y="452" font-family="Verdana, Arial, sans-serif" font-size="24" fill="#5F6374">Contraction Timer &amp; Kick Count</text>
</svg>`;

const jobs = [
  ['assets/icon.png', icon, 1024, 1024, false],
  ['assets/adaptive-icon-foreground.png', adaptiveFg, 1024, 1024, true],
  ['assets/adaptive-icon-monochrome.png', mono, 1024, 1024, true],
  ['assets/splash-icon.png', splash, 1024, 1024, true],
  ['store/icon-512.png', icon, 512, 512, false],
  ['store/feature-graphic-1024x500.png', feature, 1024, 500, false],
];

mkdirSync(resolve(root, 'assets'), { recursive: true });
mkdirSync(resolve(root, 'store'), { recursive: true });
const browser = await chromium.launch();
for (const [file, markup, w, h, transparent] of jobs) {
  const page = await browser.newPage({ viewport: { width: w, height: h }, deviceScaleFactor: 1 });
  await page.setContent(`<html><body style="margin:0;background:transparent">${markup.replace(/width="\d+" height="\d+"/, `width="${w}" height="${h}"`)}</body></html>`);
  await page.screenshot({ path: resolve(root, file), omitBackground: transparent, clip: { x: 0, y: 0, width: w, height: h } });
  await page.close();
  console.log('wrote', file);
}
await browser.close();
writeFileSync(resolve(root, 'assets/.generated'), 'Generated by scripts/make-assets.mjs\n');
